name: Frontend docker app
on:
  push: 
    branches: 
      - main

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Build docker image
        uses: docker build -t frontend-app .


        
      
